openapi: 3.0.0
info: 
  title: Konnect Application Document schema
  description: Konnect Application Document schema
  version: 0.9.3
paths:

components:
  schema:
    CorrespondenceDetails:
      type: object
      properties:
        Address: 
          $ref: "./core.yml/components/schema/Address"
        Contact:
          $ref: "./core.yml/components/schema/Contact"
          # TODO: add a regex for email

    LoanApplicationDoc:
    type: object
    properties:
      LoanApplicationBasicInfo:
        type: object
        properties:
          sector:
            $ref: "./core.yml/components/schema/Domain" 
          project_type:
            $ref: "./core.yml/components/schema/Domain" 
          district:
            $ref: "./core.yml/components/schemas/District"
          block:
            $ref: "./core.yml/components/schemas/Block"
          branch:
            type: string 
            # (if required can be shifted to $ref: "#/schemas/Provider/tags/branch" )
          amount:
            $ref: "./core.yml/components/schemas/Price"
      ApplicantDetails:
      # Approach 1
      #   $ref: "./core/schemas/Person"
      #   required_tags:
      #     PANCard:
      #       $ref: "#/schemas/Document"
      #     AadharCard:
      #       $ref: "#/schemas/Document"
      #     EducationalQualification:
      #       $ref: "#/schemas/Document"
      #     MaritalStatus:

# ==================================================================================== #          
      # Approach 2
        type: object
        properties:
          BasicDetails:
            $ref: "#/schemas/Person"
            required:
              - name
              - gender
              - dob #Age can be calculated from this no need to add it
              - tags.marital_status
              - tags.fathers_name
              - tags.mothers_name

          PANCardNumber:  
            type: string
          AadharNumber: 
            type: number
            # changed this from type document to string, since it'll just be the number and we can add the document in the documents field of the order
                 
        TemporaryCorrespondenceDetails:
          $ref: "#/schemas/CorrespondenceDetails"

        PermanentCorrespondenceDetails:
          $ref: "#/schemas/CorrespondenceDetails"

        IncomeDetails:
          type: object
          properties:
            AgriculturalIncomeSource: string
            AgriculturalIncome: number
            OtherIncomeSource:
              type: array
              items: 
                type: string
              
            OtherIncome:
              type: number
              
            TotalIncome:
              type: number
        
        SecurityDetails:
          type: object
          properties:
            # TODO: blocker on Anay

        GuarantorDetails:
          type: object
          properties:
            name: 
              $ref: './core/yml/components/schema/Person/name'
            relationship:
              type: string
            mobile:
              type: number
            email: 
              type: string # TODO: add regex for email here
            PANCardNumber:
              $ref: '#/schema/ApplicantDetails/PANCardNumber'
            
            
              
